### PR TITLE
Logo tracking improvements

### PR DESCRIPTION
**Pull request by connorshea**
Two main changes in this PR:
- Improves the [tracking](http://graphicdesign.stackexchange.com/questions/2606/difference-between-kerning-vs-letter-spacing) of the wordmark in the Rails logo. The spacing between the R and A in the initial logo is very small, whereas between the A I and L there's significantly more space. That bothered me a lot, so I wanted to try balancing the spacing.
- Logo is now smaller, 2727 bytes -> 1839 bytes. Removed Illustrator metadata, removed unnecessary (invisible) SVG elements, and minified.

Before:
rails-logo

After:
rails-logo2

Comparison (red is before, blue is after):
rails-logo-compare

### CODE REVIEW

**Comment by dhh** [comment]
Sweet! Thanks!

**Comment by connorshea** [comment]
Would you like me to open a PR for this change in the weblog as well? :D

**Comment by dhh** [comment]
@asianmack I wonder if we can put all the other uses of the logo in this repo as well, so any logo updates can be spread around easily?

**Comment by dhh** [comment]
@connorshea Please do!

**Comment by asianmack** [comment]
@connorshea I dig it!

@dhh Sounds good. What should I do, or do you wanna do that?

**Comment by dhh** [comment]
@asianmack If you could put in all the sources, that'd be great. Don't know if we just have those in final rendered form or? I'm thinking about the contributor headers etc.

**Pull request merged**
