### PR TITLE
Logo modifications

### PR DESCRIPTION
**Pull request by gavlak**
Hi,

I saw the Rails logo on Twitter and thought it can be modified a little bit. I mostly fixed small details, like letters and kerning. Only big thing changed are the "sleepers" under the arch. I tried to give them more unified look while keeping the feel of the previous logo.

screenshot
left - old, right - new

### CODE REVIEW

**Comment by dhh** [comment]
Really lovely! This is my favorite alteration so far. /cc #28

**Comment by dhh** [comment]
Actually, just going to go ahead and merge this. If others want to continue to riff based on this, go ahead.

@gavlak Can you update the other PSDs to produce the other headers we need?

**Comment by gavlak** [comment]
@dhh I'm on it.

**Comment by dhh** [comment]
Can you apply these changes to the rails/weblog repo as well? Thanks!

**Comment by gavlak** [comment]
@dhh Sure. I created new pull request in rails/weblog.

**Comment by prasanthrubyist** [comment]
Looking good...!!

**Comment by dixpac** [comment]
Sexy!

**Comment by jonathansimmons** [comment]
Looks great! Glad we got improvements in.

**Comment by duykhoa** [comment]
Look great!

**Comment by kwhaler** [comment]
Well done

**Pull request merged**
