### PR TITLE
Add baseurl for assets

### PR DESCRIPTION
**Pull request by vis-kid**
Add baseurl to config file
Add baseurl to asset link in head tag
Add baseurl to image asset paths

### CODE REVIEW

**Comment by vis-kid** [comment]
@pixeltrix ready to go :)

**Comment by pixeltrix** [comment]
@vis-kid okay, I've updated the repo settings to use master for GH pages and set master to the default branch - should I merge this now?

**Comment by rafaelfranca** [comment]
:+1:

**Comment by vis-kid** [comment]
@pixeltrix Since you mentioned the differences between branches I suggest I open another PR that is now based on the current `master`.

**Comment by pixeltrix** [comment]
Closing due to being stale

**Pull request closed without merging**
