### PR TITLE
Mention Gitlab too!

### PR DESCRIPTION
**Pull request by skyscooby**
Very popular open source project built with Rails.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. There are many popular projects built with Rails and if we were going to link to all of them in our homepage for sure we would still be missing some. Because of that, we prefer to keep this list small with those companies that are already there.

**Comment by skyscooby** [comment]
@rafaelfranca  Really Lame??

https://github.com/rails/homepage/commit/44cdd54aeb667bbcf63673c49bdc858a08600231#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by skyscooby** [comment]
"Used by more than 100,000 organizations around the globe"

**Comment by rafaelfranca** [comment]
To be fair, that is a Rails core member adding the company that he works for. What I'm trying to discourage rejecting this PR is people to submit PRs to add their companies.

While I think GitLab should probably be part of that list, I really don't want people to be sending PRs to add their companies to this list. So, as a compromise I'll discuss with the Rails core team if we should add GitLab and I'll commit myself. That way, our message is clear, "no PRs to add your companies", but the core team wanting to add is fine.

**Pull request closed without merging**
