### PR TITLE
A proposal for a new logo for Rails

### PR DESCRIPTION
**Pull request by dperrera**
Hi Rails Team,

I'm an admirer of the project so I took a stab at a logo refinement for Rails that keeps inline with the spirit of the original logo but meets the brief that Rails should be warm, approachable, and welcoming:

proposed-rails-logo

I chose Montserrat (available on Google fonts), a beautiful, geometric sans-serif face, and lost the all-uppercase treatment so the overall look is more approachable. I also revisited the train track mark to make it look more like tracks and work better at smaller sizes. The result is a mark that looks lighter, friendlier toward newcomers, and more trustworthy. 

If this is something you're interested in, please let me know. I'd be happy to work with you to pull this together.

Thanks,
Dan

### CODE REVIEW

**Comment by gertig** [comment]
Nicely done!

**Comment by jonathansimmons** [comment]
I think the actual railway track is infinitely better, though it's a pretty far separation from the old logo. 

I like the cleanest of this Montserrat font but wonder if the team was going for a slab look for a reason. Did you consider a slab font with this track mark?

**Comment by dperrera** [comment]
Thanks @jonathansimmons, I spent a bunch of time on the tracks. I agree that it does look significantly different from the original but that's only because I couldn't manage to make the mark *not* look a tentacle when the middle was filled in, especially at small sizes. 

I chose Montserrat for it's softer features to support an approachable and welcoming feel that @dhh [wrote about](http://weblog.rubyonrails.org/2016/1/19/new-rails-identity/). I looked at a bunch of different typefaces but ruled out slab-serifs because of their more structured feel and because they visually interfere with the tracks. And Montserrat happens to work beautifully with Georgia and the awesome illustrations on the updated website.

**Comment by dhh** [comment]
Dan, thanks a bunch for such a considered pitch. Really cool! Very much appreciate it.

In the end, it's a change too far for me. I like the continuity we have with the new logo. Rails 5 isn't a reboot, it's a modernization and a tilt. The logo should follow the same.

That said I'm happy to see further refinement on the direction we have with the logo. Cleaning up the type etc.

**Comment by salvomania** [comment]
I always thought that was supposed to be a tentacle in the logo.

**Comment by dperrera** [comment]
@dhh Thanks for the reply. Sorry to hear that it's not what you were looking for. I saw a proposed type improvement floating around Twitter yesterday [that was well considered](https://twitter.com/mantia/status/689623475548336128), maybe that person can be convinced to make a PR?

**Comment by m5o** [comment]
>  I saw a proposed type improvement floating around Twitter yesterday [that was well considered](https://twitter.com/mantia/status/689623475548336128), maybe that person can be convinced to make a PR?

:bell: *ping* @mantia

**Comment by connorshea** [comment]
I really like mantia's wordmark paired with the current Rails logo.

**Comment by jonathansimmons** [comment]
I took another stab at this in #28. Please have a look.

**Pull request closed without merging**
