### PR TITLE
Added translation functionality

### PR DESCRIPTION
**Pull request by dmitriy-strukov**
Hi guys! I added functionality to add translations for Rails doctrine in different languages. It's simple js switcher for beginning, If there are more translations we can connect database.

### CODE REVIEW

**Comment by dmitriy-strukov** [comment]
@dhh Could you please review?

**Comment by dhh** [comment]
Hey, thanks for working on this! I'd prefer to keep JavaScript out of this. Let's just use doctrine.html.<language-code>. Then we can also link directly to the translations.

**Comment by dmitriy-strukov** [comment]
@dhh Thanks for review! I added prefix (/en /ru) for different translations, but question is where users can look at all languages. My proposition to make some fixed div at right corner of the screen or ul list at top of page.

**Comment by dhh** [comment]
I like the idea of just having a small note at the top, maybe as part of the byline, that links to the translations. But let's keep the /doctrine permalink in the English form without a redirect or whatever. There's already endless links around the net to that page. Then we can have /doctrine/ru and other translations linked below that.

Thanks for working on this!

**Comment by dmitriy-strukov** [comment]
@dhh ok, added changes. Please merge, if it all is ok

**Comment by dhh** [comment]
I don't see the link from the english version to the russian translation?

**Comment by dmitriy-strukov** [comment]
@dhh Sorry, a little bit misunderstood you, added link

**Comment by dhh** [comment]
Sorry. Had to revert. The styling isn't right: https://github.com/rails/homepage/pull/84. Needs someone with design chops to make this presentable.

**Comment by dmitriy-strukov** [comment]
@dhh I can find a designer or maybe designer who did an existing design can help?

**Pull request merged**
