### PR TITLE
Add hover and improve navbar

### PR DESCRIPTION
**Pull request by vis-kid**
Fix broken navbar
# Current nav

screen shot 2016-09-20 at 7 46 10 pm
# Fixed

screen shot 2016-09-20 at 7 44 05 pm
# Logo with hover

screen shot 2016-09-20 at 7 44 13 pm

### CODE REVIEW

**Comment by dhh** [comment]
Which browser is showing the wrapping? I can't see it in Chrome.

image

**Comment by vis-kid** [comment]
Chrome on Mac on 100%

screen shot 2016-09-20 at 9 45 48 pm

screen shot 2016-09-20 at 9 42 37 pm

**Comment by dhh** [comment]
I'm on 53.0.2785.116 and don't see this. Also a Mac. Maybe a version issue?

**Comment by vis-kid** [comment]
Sure, could be. I lack the experience to exactly pinpoint the issue and exclude all possible reasons. The logo was previously placed in a `section` outside the navigation. Maybe that?
Think that the navbar is a good home for the logo in any case…
For making the site responsive, this will be a handy move as well…

**Comment by pixeltrix** [comment]
Closing due to being stale

**Pull request closed without merging**
