### PR TITLE
Add baseurl for assets

### PR DESCRIPTION
**Pull request by vis-kid**
Add baseurl to config file
Add baseurl to asset link in head tag
Add baseurl to image asset paths

### CODE REVIEW

**Comment by vis-kid** [comment]
@pixeltrix 
here you go!

FYI, last time @rafaelfranca merged the same PR into `gh-pages`, `base-url` didn’t work and the assets where not available and he had to revert right away.

Our hope was that it was due to some Jekyll GH-Pages magic and would be also resolved after switching to `master`. If it doesn’t work as well, I will do some more detective work to figure this out.

In any case though, developing against master and being able to freely push changes to `gh-pages` on your own fork was well worth the trouble and makes for a smoother experience for new design contributions I think.

Thank you!

**Comment by pixeltrix** [comment]
@vis-kid on a train with spotty internet connection - will wait until I get home before merging in case I have to do an 🚨 revert 😄

**Comment by vis-kid** [comment]
sure, makes total sense! 😄

**Comment by pixeltrix** [comment]
@vis-kid good job I waited because it broke when I merged it:

rubyonrails

**Comment by vis-kid** [comment]
Damn! Wonder why it’s not working as expected. The Sinatra site had no problems with this setup…

**Comment by vis-kid** [comment]
@pixeltrix Do you think the excluded `- CNAME` in `_config` can be the perpetrator?
The other difference I see between this site and the Sinatra one is that Sinatra uses `www.` in the `CNAME`

**Pull request merged**
