### PR TITLE
Middleman-ize site.

### LINKED ISSUE #7: Proper redirects
It would be great to have redirects for all the old links like http://rubyonrails.org/core -> http://rubyonrails.org/community#core.

### PR DESCRIPTION
**Pull request by maclover7**
- Fixes #7, #15, #16
- cc @dhh @sgrif
- **TODO**: Will investigate whether we need to have Travis build and publish the site onto the `gh-pages` branch, and have the site source be on `master`.

### CODE REVIEW

**Comment by sgrif** [comment]
Can we verify that this does in fact fix the trailing slash issue?

**Comment by maclover7** [comment]
If you look in URL bar, there is no slash:

screen shot 2016-01-19 at 8 28 53 pm

**Comment by sgrif** [comment]
Visiting with a slash redirects though, correct?

**Comment by maclover7** [comment]
Both work, with and without the slash. Why do we need a redirect?

**Comment by sgrif** [comment]
Existing links both those that we do control, and those that we don't.
Currently trailing slashes cause a 404.

**Comment by maclover7** [comment]
I don't see why we need to redirect `/maintenance/` to `maintenance` -- with the new rig, both will work fine.

**Comment by sgrif** [comment]
As I said in my previous comment, because there are existing links to `/maintenance/` that we don't control, which are currently 404ing

**Comment by maclover7** [comment]
If we want to redirect trailing slashes, the only way I'm able to get it to work locally (remove slash and redirect) is if we add a `config.ru` and go through Rack. Is this something we want to do -- it would require us to move off of static hosting. Not sure if I'm looking at this the wrong way.

Already tried something like this in config.rb, but didn't work:
```ruby
redirect '/maintenance', to: '/maintenance'
```

**Comment by sgrif** [comment]
Ah, I thought middleman handled this for us out of the box.

**Comment by matthewd** [comment]
If we use a site generator, I imagine we'd use Jekyll, as the old site did. We don't need any of Middleman's more complex tricks, and Jekyll is The GH Pages Way.

But @dhh would prefer we stick to raw HTML, unless we hit something that absolutely needs it. (Redirects may be that thing.)

**Comment by sgrif** [comment]
Would copying every `foo.html` file into `foo/index.html` allow trailing slashes or am I imagining that?

**Comment by maclover7** [comment]
^ Having the site in the [old directory structure](https://github.com/rails/rails.github.com) would not allow redirects from trailing slashes to without. Not sure what the best solution here is.

**Comment by matthewd** [comment]
If just renaming `foo.html` to `foo/index.html` solves the slash problem (it really doesn't matter which is canonical, as long as one will redirect to the other), then let's do that. Sorting out redirects for actually-changed URLs can come later.

**Comment by maclover7** [comment]
Just so we're all on the same page, the idea is to (for example):
- get rid of `/maintenance/` and just have it redirect to `/maintenance`
- have `/maintenance` be the main route

@sgrif can you confirm that's what our goal is here? I don't think any static site generator is going to let us do this -- I think we're going to have to use Middleman in tandem with a small Rack `config.ru`.

**Comment by matthewd** [comment]
> it really doesn't matter which is canonical, as long as one will redirect to the other

**Comment by matthewd** [comment]
> a small Rack config.ru

That's.. not gonna work.

**Comment by pixeltrix** [comment]
One option is to put a free CloudFlare account in front of the site - that way we can have SSL support and we can use the page rules feature for redirects.

**Comment by maclover7** [comment]
Since the site is pretty much all static, I'm fine to host on a free Heroku instance.

**Pull request closed without merging**
