### PR TITLE
Add a link to Rails forum

### PR DESCRIPTION
**Pull request by morgoth**
I guess it's worth to add it to the main navigation

### CODE REVIEW

**Comment by jonathanhefner** [comment]
I do think it would be helpful to add this, but it causes some unfortunate wrapping (at least on my screen):
rails-homepage-discuss-link

Perhaps the CSS could be tweaked to prevent this?

https://github.com/rails/homepage/blob/b838fda677c1e11c7dedaf2f7670992df097b868/style.css#L57-L58

Also, what do you think of "Forum" vs "Discuss"?  "Discuss" matches with "Ask" and "Contribute", but "Forum" matches with "Blog", "Guides", and "API".  I'm not sure which is better.

**Comment by morgoth** [comment]
@jonathanhefner As it goes for styling - it looked fine on Chrome, but indeed broke on Firefox. I changed the margin, but now it is little dense. Other option would be to remove "Ask for help" link as looks like @rafaelfranca wanted to do this in https://github.com/rails/homepage/pull/117/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL10

**Comment by rafaelfranca** [comment]
Yes, let's remove the "Ask for help" in favor of the discuss link.

**Comment by morgoth** [comment]
@rafaelfranca Updated

**Pull request merged**
