### PR TITLE
Logo Adjustments

### PR DESCRIPTION
**Pull request by jonathansimmons**
This is another proposal for a logo refinement. After seeing @dhh response to #19 this attempt tries to stay a bit more true to the design that the team initially landed on while cleaning up the type and reworking the rail a bit. 

This is not perfect and I'm sure someone with more illustration skills could clean the rail up a touch more than I have. I hope this can be considered. 

screen shot 2016-01-21 at 11 05 05 pm

image

### CODE REVIEW

**Comment by wachunei** [comment]
This is pretty similar to this one https://twitter.com/mantia/status/689623475548336128, I also hope these get considered.

**Comment by jonathansimmons** [comment]
This does take a lot of queues from that version, though it is different. 

Mantia's version was pretty well regarded on the internet so I figured it was a good point of reference.

**Comment by dhh** [comment]
Hmm, I like some elements of the wordmark fixes, like the equal size gaps for the R and A holes, but I don't like the rounded corners compared to the Borgstrand font. I don't like the revised rail arc. Thanks a bunch of playing with this! Great to see open source working for logo tweaks too.

**Comment by salvomania** [comment]
The "S" in the "before" logo has some issues. The "R" is a little strange as well, especially as it relates to the form of the "A." Is this a hand-drawn face? It seems a little clumsy.

**Comment by dhh** [comment]
Happy to see all that cleaned up. It's the Borgstrand font:
http://www.fountaintype.com/typefaces/borgstrand

**Comment by salvomania** [comment]
Hmmmm---the "R," "A," and "S" all seem to be modified compared to the original Borgstrand font.

**Comment by connorshea** [comment]
We'll need @asianmack to help with this, I think. None of us but him have a license for Borgstrand, and I'd personally rather not pay the €49 for a license to it.

**Comment by asianmack** [comment]
FYI the font is in /materials. Please go for it.

**Comment by asianmack** [comment]
The logotype is exactly the same as the original Rails logo save for tighter kerning.

ruby_on_rails svg

**Comment by connorshea** [comment]
Based on the Fountaintype website, I don't believe you're legally able to redistribute the font in this manner. I could be wrong, but I'd err on the side of caution here.

**Comment by asianmack** [comment]
OK separate from that. The font is not modified. So not sure what you're wanting to do.

**Comment by dhh** [comment]
Closed in favor of #30.

**Pull request closed without merging**
