### PR TITLE
Add redirects for old pages. Closes #7

### LINKED ISSUE #7: Proper redirects
It would be great to have redirects for all the old links like http://rubyonrails.org/core -> http://rubyonrails.org/community#core.

### PR DESCRIPTION
**Pull request by jyunderwood**
This closes issue #7 by adding the specified redirects for old pages.

cc @matthewd

### CODE REVIEW

**Comment by sonalkr132** [comment]
hi, Doesn't adding [redirect_from](https://github.com/jekyll/jekyll-redirect-from#usage) to existing pages makes more sense? You won't need to add all these new files.

**Comment by dhh** [comment]
Please do send a PR with that change!

**Comment by jyunderwood** [comment]
@sonalkr132 That would work for the two pages that redirect to the homepage, but the pages that redirect to external sites or redirect to pages with anchors, stub pages are needed. So I kept all redirects consistent in this PR for clarity.

**Comment by sonalkr132** [comment]
> but the pages that redirect to external sites or redirect to pages with anchors, stub pages are needed.

@jyunderwood, I see it now.
 
> I kept all redirects consistent in this PR for clarity.

You just need to add following in index page instead of a new files for each of them:
```Ruby
redirect_from:
  - /deploy/
  - /quotes/
  - /screencasts/
```

**Pull request closed without merging**
